### ISSUE TITLE
GET a Error

### ISSUE THREAD

**Issue by markddd268** [faush01/StrmExtract#1]
2024-02-13 12:12:20.596 Info Server: http/1.0 Response 404 to 127.0.0.1. Time: 0ms. GET http://host1/embywebsocket?api_key=*********
2024-02-13 12:12:52.069 Info Server: http/1.0 POST http://host1/emby/ScheduledTasks/Running/5a9c725ddfe1cbc21b4d2e3044f93ac6?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=***************&X-Emby-Client-Version=4.8.1.0&X-Emby-Token=x_secret2_x&X-Emby-Language=zh-cn. UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
2024-02-13 12:12:52.069 Info Server: http/1.0 Response 204 to 127.0.0.1. Time: 0ms. POST http://host1/emby/ScheduledTasks/Running/5a9c725ddfe1cbc21b4d2e3044f93ac6?X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=************&X-Emby-Client-Version=4.8.1.0&X-Emby-Token=x_secret2_x&X-Emby-Language=zh-cn
2024-02-13 12:12:52.069 Info TaskManager: Executing Process Strm targets
2024-02-13 12:12:52.069 Info App: StrmExtract - Task Execute
2024-02-13 12:12:52.070 Info App: StrmExtract - Number of items before : 5
2024-02-13 12:12:52.070 Info App: StrmExtract - Item dropped : 红辣椒 - /docker/auto_symlink/Media/红辣椒 (2006)/红辣椒 (2006).strm - MediaBrowser.Controller.Entities.Movies.Movie - 1
2024-02-13 12:12:52.070 Info App: StrmExtract - Item dropped : 进击的巨人：后篇 ~自由之翼~ - /docker/auto_symlink/Media/进击的巨人：后篇 ~自由之翼~ (2015)/进击的巨人：后篇 ~自由之翼~ (2015).strm - MediaBrowser.Controller.Entities.Movies.Movie - 1
2024-02-13 12:12:52.071 Info App: StrmExtract - Item dropped : 命运石之门：负荷领域的既视感 - /docker/auto_symlink/Media/命运石之门：负荷领域的既视感 (2013)/命运石之门：负荷领域的既视感 (2013).strm - MediaBrowser.Controller.Entities.Movies.Movie - 1
2024-02-13 12:12:52.071 Info App: StrmExtract - Item dropped : 进击的巨人 ~觉醒的咆哮~ - /docker/auto_symlink/Media/进击的巨人 ~觉醒的咆哮~ (2018)/进击的巨人 ~觉醒的咆哮~ (2018).strm - MediaBrowser.Controller.Entities.Movies.Movie - 1
2024-02-13 12:12:52.071 Info App: StrmExtract - Item dropped : 进击的巨人：前篇 ~红莲之弓矢~ - /docker/auto_symlink/Media/进击的巨人：前篇 ~红莲之弓矢~ (2014)/进击的巨人：前篇 ~红莲之弓矢~ (2014).strm - MediaBrowser.Controller.Entities.Movies.Movie - 1
2024-02-13 12:12:52.071 Info App: StrmExtract - Number of items after : 0
2024-02-13 12:12:52.071 Info App: StrmExtract - Task Complete
2024-02-13 12:12:52.071 Info TaskManager: Process Strm targets Completed after 0 minute(s) and 0 seconds

**Comment by markddd268** [comment]
> 2024-02-12 18:37:10.060 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /opt/emby-server/bin/ffprobe -i "https://*******.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data 2024-02-12 18:37:10.144 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0 - Succeeded 2024-02-12 18:37:10.145 Error App: Error in ffprobe *** Error Report *** Version: 4.8.1.0 Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb Operating system: Linux version 5.10.0-13-amd64 ([debian-kernel@lists.debian.org](mailto:debian-kernel@lists.debian.org)) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 Framework: .NET 6.0.25 OS/Process: x64/x64 Runtime: opt/emby-server/system/System.Private.CoreLib.dll Processor count: 2 Data path: /var/lib/emby Application path: /opt/emby-server/system Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: Emby.Server.MediaEncoding.Unified.Ffmpeg.FfRunException: ffprobe failed - streams and format are both null: -i "https://*******9.mkv" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC built with gcc 10.3.0 (crosstool-NG 1.25.0) [tcp @ 0x152ab40] Failed to resolve hostname _**: Name or service not known https://**_/.mkv: Input/output error
> 
> ```
> {
> 
> }
>    at Emby.Server.MediaEncoding.Probing.MediaProbeManager.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, String userAgent, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Boolean hasMixedProtocols, CancellationToken cancellationToken)
>    at Emby.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](MetadataResult`1 metadataResult, MetadataRefreshOptions options, LibraryOptions libraryOptions, CancellationToken cancellationToken)
>    at Emby.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, MetadataResult`1 itemResult, String logName, MetadataRefreshOptions options, LibraryOptions libraryOptions, RefreshResult refreshResult, CancellationToken cancellationToken)
> Source: Emby.Server.MediaEncoding
> TargetSite: Void MoveNext()
> ```

ohhhhh.  i,get..."Failed to resolve hostname"
